module HomePage exposing (main)

import Html exposing (..)
import Html.Attributes exposing (..)


view model =
    div [ class "jumbotron" ]
        [ h1 [] [ text "Welcome to electron renderer!" ]
        , p []
            [  text <|
                """
                You are viewing material generated by the Elm DOM
                """
            ]
        ]


main =
    view "dummy model"
